/*Oluþturulan Tablolar dolduruldu.*/
Use DijitalOyun

INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(1,100000,'Activision')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(2,50000,'Sony Interactive Entertainment')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(3,1000,'Microsoft')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(4,70000,'EA')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(5,90000,'Nintendo')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(6,20000,'Telltale Games')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(7,50000,'Take-Two Interactive')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(8,70000,'Konami')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(9,30000,'Paradox Interactive')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(10,40000,'Deep Silver')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(11,70000,'Ubisoft')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(12,50000,'CD Projekt')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(13,10000,'InnerSloth')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(14,2000000,'Rockstar Games')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(15,700000,'Valve')
INSERT INTO Yayýncý (Yayýncý_id,Yayýncý_Ciro,Yayýncý_isim) VALUES(16,500000,'Riot Games')

INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(1,5000,'Sony Interactive Entertainment')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(2,7000,'Microsoft')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(3,50000,'Ubisoft')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(4,30000,'Bioware')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(5,40000,'Nintendo')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(6,7000,'Deep Silver')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(7,5900,'Konami')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(8,60000,'Telltale Games')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(9,7000,'EA')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(10,100000,'Paradox Interactive')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(11,100000,'Activision')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(12,10000,'Take-Two Interactive')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(13,200000,'CD Projekt Red')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(14,10000,'InnerSloth')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(15,2000000,'Rockstar Games')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(16,700000,'Valve')
INSERT INTO Geliþtirici (Geliþtirici_id,Geliþtirici_Ciro,Geliþtirici_isim) VALUES(17,500000,'Riot Games')

INSERT INTO Kategori (Kategori_id,Kategori_isim,Oyun_Sayýsý) values(1,'RYO',5000)
INSERT INTO Kategori (Kategori_id,Kategori_isim,Oyun_Sayýsý) values(2,'Aksiyon',7000)
INSERT INTO Kategori (Kategori_id,Kategori_isim,Oyun_Sayýsý) values(3,'Macera',6000)
INSERT INTO Kategori (Kategori_id,Kategori_isim,Oyun_Sayýsý) values(4,'Strateji',2000)
INSERT INTO Kategori (Kategori_id,Kategori_isim,Oyun_Sayýsý) values(5,'Baðýmsýz',50000)
INSERT INTO Kategori (Kategori_id,Kategori_isim,Oyun_Sayýsý) values(6,'Platform',7000)
INSERT INTO Kategori (Kategori_id,Kategori_isim,Oyun_Sayýsý) values(7,'Çok Oyunculu',8000)
INSERT INTO Kategori (Kategori_id,Kategori_isim,Oyun_Sayýsý) values(8,'Yarýþ',5000)
INSERT INTO Kategori (Kategori_id,Kategori_isim,Oyun_Sayýsý) values(9,'Simulasyon',20000)
INSERT INTO Kategori (Kategori_id,Kategori_isim,Oyun_Sayýsý) values(10,'Early Access',3000)

INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (1,'20190506','Anthem',180,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='Bioware'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='EA'))
INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (2,'20120506','Crusader Kings 2',80,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='Paradox Interactive'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='Paradox Interactive'))
INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (3,'20200506','COD MW2',175,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='Bioware'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='Activision'))
INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (4,'20160506','Batman The Telltale Series',333,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='Telltale Games'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='Telltale Games'))
INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (5,'20190506','The Crew 2',64,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='Ubisoft'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='Ubisoft'))
INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (6,'20190506','Metro Exodus',180,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='Deep Silver'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='Deep Silver'))
INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (7,'20190506','NBA 2K',480,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='Take-Two Interactive'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='EA'))
INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (8,'20190506','Hollow Knight',32,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='Microsoft'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='Microsoft'))
INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (9,'20190506','Mario',9,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='Nintendo'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='Nintendo'))
INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (10,'20190506','Gears of War',74,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='Microsoft'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='Microsoft'))
INSERT INTO Oyun (Oyun_id,Çýkýþ_Tarihi,Oyun_ismi,Oyun_fiyatý,Geliþtirici_id,Yayýncý_id) VALUES (11,'20190506','Witcher',16,(SELECT Geliþtirici_id From Geliþtirici WHERE Geliþtirici_isim='CD Projekt Red'),(SELECT Yayýncý_id FROM Yayýncý where Yayýncý_isim='CD Projekt'))


INSERT INTO Ýtem (Ýtem_id,Ýtem_isim,Oyun_id) Values (1,'a',(SELECT Oyun_id FROM Oyun WHERE Oyun_ismi='Anthem'))
INSERT INTO Ýtem (Ýtem_id,Ýtem_isim,Oyun_id) Values (2,'b',(SELECT Oyun_id FROM Oyun WHERE Oyun_ismi='Witcher'))
INSERT INTO Ýtem (Ýtem_id,Ýtem_isim,Oyun_id) Values (3,'c',(SELECT Oyun_id FROM Oyun WHERE Oyun_ismi='COD MW2'))
INSERT INTO Ýtem (Ýtem_id,Ýtem_isim,Oyun_id) Values (4,'d',(SELECT Oyun_id FROM Oyun WHERE Oyun_ismi='The Crew 2'))
INSERT INTO Ýtem (Ýtem_id,Ýtem_isim,Oyun_id) Values (5,'f',(SELECT Oyun_id FROM Oyun WHERE Oyun_ismi='Metro Exodus'))
INSERT INTO Ýtem (Ýtem_id,Ýtem_isim,Oyun_id) Values (6,'g',(SELECT Oyun_id FROM Oyun WHERE Oyun_ismi='NBA 2K'))
INSERT INTO Ýtem (Ýtem_id,Ýtem_isim,Oyun_id) Values (7,'h',(SELECT Oyun_id FROM Oyun WHERE Oyun_ismi='Hollow Knight'))
INSERT INTO Ýtem (Ýtem_id,Ýtem_isim,Oyun_id) Values (8,'k',(SELECT Oyun_id FROM Oyun WHERE Oyun_ismi='Mario'))
INSERT INTO Ýtem (Ýtem_id,Ýtem_isim,Oyun_id) Values (9,'j',(SELECT Oyun_id FROM Oyun WHERE Oyun_ismi='Gears of War'))
INSERT INTO Ýtem (Ýtem_id,Ýtem_isim,Oyun_id) Values (10,'v',(SELECT Oyun_id FROM Oyun WHERE Oyun_ismi='Batman The Telltale Series'))

INSERT INTO Aittir(Aitlik_id,Oyun_id,Kategori_id) VALUES (1,(SELECT Oyun_id from Oyun WHERE Oyun_ismi='NBA 2K'),(SELECT Kategori_id from Kategori WHERE Kategori_isim='Simulasyon'))
INSERT INTO Aittir(Aitlik_id,Oyun_id,Kategori_id) VALUES (2,(SELECT Oyun_id from Oyun WHERE Oyun_ismi='Anthem'),(SELECT Kategori_id from Kategori WHERE Kategori_isim='RYO'))
INSERT INTO Aittir(Aitlik_id,Oyun_id,Kategori_id) VALUES (3,(SELECT Oyun_id from Oyun WHERE Oyun_ismi='COD MW2'),(SELECT Kategori_id from Kategori WHERE Kategori_isim='Aksiyon'))
INSERT INTO Aittir(Aitlik_id,Oyun_id,Kategori_id) VALUES (4,(SELECT Oyun_id from Oyun WHERE Oyun_ismi='Hollow Knight'),(SELECT Kategori_id from Kategori WHERE Kategori_isim='Macera'))
INSERT INTO Aittir(Aitlik_id,Oyun_id,Kategori_id) VALUES (5,(SELECT Oyun_id from Oyun WHERE Oyun_ismi='Batman The Telltale Series'),(SELECT Kategori_id from Kategori WHERE Kategori_isim='Early Access'))
INSERT INTO Aittir(Aitlik_id,Oyun_id,Kategori_id) VALUES (6,(SELECT Oyun_id from Oyun WHERE Oyun_ismi='Witcher'),(SELECT Kategori_id from Kategori WHERE Kategori_isim='RYO'))
INSERT INTO Aittir(Aitlik_id,Oyun_id,Kategori_id) VALUES (7,(SELECT Oyun_id from Oyun WHERE Oyun_ismi='Metro Exodus'),(SELECT Kategori_id from Kategori WHERE Kategori_isim='Aksiyon'))
INSERT INTO Aittir(Aitlik_id,Oyun_id,Kategori_id) VALUES (8,(SELECT Oyun_id from Oyun WHERE Oyun_ismi='Mario'),(SELECT Kategori_id from Kategori WHERE Kategori_isim='Macera'))
INSERT INTO Aittir(Aitlik_id,Oyun_id,Kategori_id) VALUES (9,(SELECT Oyun_id from Oyun WHERE Oyun_ismi='The Crew 2'),(SELECT Kategori_id from Kategori WHERE Kategori_isim='Yarýþ'))
INSERT INTO Aittir(Aitlik_id,Oyun_id,Kategori_id) VALUES (10,(SELECT Oyun_id from Oyun WHERE Oyun_ismi='Gears of War'),(SELECT Kategori_id from Kategori WHERE Kategori_isim='Aksiyon'))

INSERT INTO Kullanýcý(Kullanýcý_id,Cüzdantutarý,Email,HesapDurumu,Level,Þifre) VALUES(1,50,'A@hotmail.com',0,1,'A')
INSERT INTO Kullanýcý(Kullanýcý_id,Cüzdantutarý,Email,HesapDurumu,Level,Þifre) VALUES(2,30,'b@hotmail.com',1,50,'B')
INSERT INTO Kullanýcý(Kullanýcý_id,Cüzdantutarý,Email,HesapDurumu,Level,Þifre) VALUES(3,40,'c@hotmail.com',0,100,'C')
INSERT INTO Kullanýcý(Kullanýcý_id,Cüzdantutarý,Email,HesapDurumu,Level,Þifre) VALUES(4,10,'d@hotmail.com',1,2,'Ç')
INSERT INTO Kullanýcý(Kullanýcý_id,Cüzdantutarý,Email,HesapDurumu,Level,Þifre) VALUES(5,20,'e@hotmail.com',0,3,'D')
INSERT INTO Kullanýcý(Kullanýcý_id,Cüzdantutarý,Email,HesapDurumu,Level,Þifre) VALUES(6,500,'g@hotmail.com',1,4,'E')
INSERT INTO Kullanýcý(Kullanýcý_id,Cüzdantutarý,Email,HesapDurumu,Level,Þifre) VALUES(7,200,'h@hotmail.com',0,5,'F')
INSERT INTO Kullanýcý(Kullanýcý_id,Cüzdantutarý,Email,HesapDurumu,Level,Þifre) VALUES(8,300,'s@hotmail.com',0,6,'G')
INSERT INTO Kullanýcý(Kullanýcý_id,Cüzdantutarý,Email,HesapDurumu,Level,Þifre) VALUES(9,200,'þ@hotmail.com',0,7,'H')
INSERT INTO Kullanýcý(Kullanýcý_id,Cüzdantutarý,Email,HesapDurumu,Level,Þifre) VALUES(10,100,'q@hotmail.com',0,8,'O')

INSERT INTO Ýstek_listesi(Ýstekliste_id,Oyun_sayýsý,Kullanýcý_id) Values(1,2,(SELECT Kullanýcý_id from Kullanýcý WHERE Kullanýcý_id=1))
INSERT INTO Ýstek_listesi(Ýstekliste_id,Oyun_sayýsý,Kullanýcý_id) Values(2,2,(SELECT Kullanýcý_id from Kullanýcý WHERE Kullanýcý_id=2))
INSERT INTO Ýstek_listesi(Ýstekliste_id,Oyun_sayýsý,Kullanýcý_id) Values(3,2,(SELECT Kullanýcý_id from Kullanýcý WHERE Kullanýcý_id=3))
INSERT INTO Ýstek_listesi(Ýstekliste_id,Oyun_sayýsý,Kullanýcý_id) Values(4,2,(SELECT Kullanýcý_id from Kullanýcý WHERE Kullanýcý_id=4))
INSERT INTO Ýstek_listesi(Ýstekliste_id,Oyun_sayýsý,Kullanýcý_id) Values(5,2,(SELECT Kullanýcý_id from Kullanýcý WHERE Kullanýcý_id=5))
INSERT INTO Ýstek_listesi(Ýstekliste_id,Oyun_sayýsý,Kullanýcý_id) Values(6,2,(SELECT Kullanýcý_id from Kullanýcý WHERE Kullanýcý_id=6))
INSERT INTO Ýstek_listesi(Ýstekliste_id,Oyun_sayýsý,Kullanýcý_id) Values(7,2,(SELECT Kullanýcý_id from Kullanýcý WHERE Kullanýcý_id=7))
INSERT INTO Ýstek_listesi(Ýstekliste_id,Oyun_sayýsý,Kullanýcý_id) Values(8,2,(SELECT Kullanýcý_id from Kullanýcý WHERE Kullanýcý_id=8))
INSERT INTO Ýstek_listesi(Ýstekliste_id,Oyun_sayýsý,Kullanýcý_id) Values(9,2,(SELECT Kullanýcý_id from Kullanýcý WHERE Kullanýcý_id=9))
INSERT INTO Ýstek_listesi(Ýstekliste_id,Oyun_sayýsý,Kullanýcý_id) Values(10,2,(SELECT Kullanýcý_id from Kullanýcý WHERE Kullanýcý_id=10))

INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(1,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=2),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=3))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(2,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=3),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=1))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(3,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=4),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=11))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(4,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=1),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=5))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(5,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=8),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=6))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(6,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=9),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=2))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(7,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=5),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=8))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(8,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=6),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=9))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(9,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=7),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=7))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(10,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=10),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=2))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(11,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=2),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=2))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(12,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=3),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=7))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(13,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=4),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=1))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(14,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=1),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=3))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(15,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=8),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=2))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(16,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=9),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=9))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(17,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=5),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=4))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(18,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=6),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=11))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(19,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=7),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=6))
INSERT INTO Bulundurur(Bulundurma_id,istek_id,Oyun_id) Values(20,(SELECT Ýstekliste_id from Ýstek_listesi Where Ýstekliste_id=10),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=5))

INSERT INTO Kopya(Seri_no,Kopya_tarihi,Kullanýcý_id,Oyun_id) Values(1,'20150804',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=2),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=3))
INSERT INTO Kopya(Seri_no,Kopya_tarihi,Kullanýcý_id,Oyun_id) Values(2,'20190706',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=1),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=4))
INSERT INTO Kopya(Seri_no,Kopya_tarihi,Kullanýcý_id,Oyun_id) Values(3,'20170804',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=7),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=6))
INSERT INTO Kopya(Seri_no,Kopya_tarihi,Kullanýcý_id,Oyun_id) Values(4,'20050804',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=5))
INSERT INTO Kopya(Seri_no,Kopya_tarihi,Kullanýcý_id,Oyun_id) Values(5,'20090804',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=9),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=10))
INSERT INTO Kopya(Seri_no,Kopya_tarihi,Kullanýcý_id,Oyun_id) Values(6,'20100804',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=1))
INSERT INTO Kopya(Seri_no,Kopya_tarihi,Kullanýcý_id,Oyun_id) Values(7,'20110804',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=8),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=9))
INSERT INTO Kopya(Seri_no,Kopya_tarihi,Kullanýcý_id,Oyun_id) Values(8,'20120804',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=10),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=2))
INSERT INTO Kopya(Seri_no,Kopya_tarihi,Kullanýcý_id,Oyun_id) Values(9,'20130804',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=7))
INSERT INTO Kopya(Seri_no,Kopya_tarihi,Kullanýcý_id,Oyun_id) Values(10,'20140804',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=9),(SELECT Oyun_id FROM Oyun WHERE Oyun_id=8))

INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(1,'20090804 10:34:09 AM',10,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=4),(select Oyun_id from Oyun where Oyun_id=1))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(2,'20090804 10:34:09 AM',30,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5),(select Oyun_id from Oyun where Oyun_id=4))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(3,'20090804 10:34:09 AM',20,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=8),(select Oyun_id from Oyun where Oyun_id=7))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(4,'20090804 10:34:09 AM',40,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=9),(select Oyun_id from Oyun where Oyun_id=5))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(5,'20090804 10:34:09 AM',50,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=4),(select Oyun_id from Oyun where Oyun_id=6))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(6,'20090804 10:34:09 AM',30,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=6),(select Oyun_id from Oyun where Oyun_id=2))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(7,'20090804 10:34:09 AM',100,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5),(select Oyun_id from Oyun where Oyun_id=3))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(8,'20090804 10:34:09 AM',1000,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=7),(select Oyun_id from Oyun where Oyun_id=8))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(9,'20090804 10:34:09 AM',500,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=8),(select Oyun_id from Oyun where Oyun_id=9))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(10,'20090804 10:34:09 AM',300,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=10),(select Oyun_id from Oyun where Oyun_id=10))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(11,'20090804 10:34:09 AM',0,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3),(select Oyun_id from Oyun where Oyun_id=11))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(12,'20090804 10:34:09 AM',70,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=10),(select Oyun_id from Oyun where Oyun_id=19))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(13,'20090804 10:34:09 AM',200,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=9),(select Oyun_id from Oyun where Oyun_id=14))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(14,'20090804 10:34:09 AM',5,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3),(select Oyun_id from Oyun where Oyun_id=17))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(15,'20090804 10:34:09 AM',20,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=1),(select Oyun_id from Oyun where Oyun_id=15))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(16,'20090804 10:34:09 AM',90,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=1),(select Oyun_id from Oyun where Oyun_id=16))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(17,'20090804 10:34:09 AM',30,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=6),(select Oyun_id from Oyun where Oyun_id=1))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(18,'20090804 10:34:09 AM',100,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=8),(select Oyun_id from Oyun where Oyun_id=13))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(19,'20090804 10:34:09 AM',700,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=4),(select Oyun_id from Oyun where Oyun_id=18))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(20,'20090804 10:34:09 AM',150,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=2),(select Oyun_id from Oyun where Oyun_id=8))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(21,'20090804 10:34:09 AM',0,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=9),(select Oyun_id from Oyun where Oyun_id=10))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(22,'20090804 10:34:09 AM',80,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3),(select Oyun_id from Oyun where Oyun_id=11))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(23,'20090804 10:34:09 AM',10,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=9),(select Oyun_id from Oyun where Oyun_id=4))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(24,'20090804 10:34:09 AM',0,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=4),(select Oyun_id from Oyun where Oyun_id=2))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(25,'20090804 10:34:09 AM',50,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3),(select Oyun_id from Oyun where Oyun_id=19))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(26,'20090804 10:34:09 AM',180,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5),(select Oyun_id from Oyun where Oyun_id=3))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(27,'20090804 10:34:09 AM',260,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=7),(select Oyun_id from Oyun where Oyun_id=7))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(28,'20090804 10:34:09 AM',18,1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=10),(select Oyun_id from Oyun where Oyun_id=16))
INSERT INTO Yorum(Yorum_id,Yorum_Tarihi,Beðeni,Pozitif_Negatif,Kullanýcý_id,Oyun_id) VALUES(29,'20090804 10:34:09 AM',34,0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=1),(select Oyun_id from Oyun where Oyun_id=19))

INSERT INTO Baþarým(Baþarým_id,Baþarým_isim,Oyun_id) VALUES(1,'a',(SELECT Oyun_id FROM Oyun WHERE Oyun_id=2))
INSERT INTO Baþarým(Baþarým_id,Baþarým_isim,Oyun_id) VALUES(2,'b',(SELECT Oyun_id FROM Oyun WHERE Oyun_id=3))
INSERT INTO Baþarým(Baþarým_id,Baþarým_isim,Oyun_id) VALUES(3,'c',(SELECT Oyun_id FROM Oyun WHERE Oyun_id=4))
INSERT INTO Baþarým(Baþarým_id,Baþarým_isim,Oyun_id) VALUES(4,'ç',(SELECT Oyun_id FROM Oyun WHERE Oyun_id=8))
INSERT INTO Baþarým(Baþarým_id,Baþarým_isim,Oyun_id) VALUES(5,'d',(SELECT Oyun_id FROM Oyun WHERE Oyun_id=9))
INSERT INTO Baþarým(Baþarým_id,Baþarým_isim,Oyun_id) VALUES(6,'e',(SELECT Oyun_id FROM Oyun WHERE Oyun_id=10))
INSERT INTO Baþarým(Baþarým_id,Baþarým_isim,Oyun_id) VALUES(7,'h',(SELECT Oyun_id FROM Oyun WHERE Oyun_id=1))
INSERT INTO Baþarým(Baþarým_id,Baþarým_isim,Oyun_id) VALUES(8,'p',(SELECT Oyun_id FROM Oyun WHERE Oyun_id=3))
INSERT INTO Baþarým(Baþarým_id,Baþarým_isim,Oyun_id) VALUES(9,'u',(SELECT Oyun_id FROM Oyun WHERE Oyun_id=4))
INSERT INTO Baþarým(Baþarým_id,Baþarým_isim,Oyun_id) VALUES(10,'q',(SELECT Oyun_id FROM Oyun WHERE Oyun_id=6))

INSERT INTO Ýstek(Ýstek_id,Kabul_Red,Tarih_Saat,Kullanýcý1_id,Kullanýcý2_id) VALUES(1,0,'20000804 11:34:09 AM',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=1),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=2))
INSERT INTO Ýstek(Ýstek_id,Kabul_Red,Tarih_Saat,Kullanýcý1_id,Kullanýcý2_id) VALUES(2,1,'20000804 11:34:09 AM',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=2),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3))
INSERT INTO Ýstek(Ýstek_id,Kabul_Red,Tarih_Saat,Kullanýcý1_id,Kullanýcý2_id) VALUES(3,1,'20000804 11:34:09 AM',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=4))
INSERT INTO Ýstek(Ýstek_id,Kabul_Red,Tarih_Saat,Kullanýcý1_id,Kullanýcý2_id) VALUES(4,0,'20000804 11:34:09 AM',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=4),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5))
INSERT INTO Ýstek(Ýstek_id,Kabul_Red,Tarih_Saat,Kullanýcý1_id,Kullanýcý2_id) VALUES(5,0,'20000804 11:34:09 AM',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=6))
INSERT INTO Ýstek(Ýstek_id,Kabul_Red,Tarih_Saat,Kullanýcý1_id,Kullanýcý2_id) VALUES(6,0,'20000804 11:34:09 AM',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=6),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=7))
INSERT INTO Ýstek(Ýstek_id,Kabul_Red,Tarih_Saat,Kullanýcý1_id,Kullanýcý2_id) VALUES(7,0,'20000804 11:34:09 AM',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=7),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=8))
INSERT INTO Ýstek(Ýstek_id,Kabul_Red,Tarih_Saat,Kullanýcý1_id,Kullanýcý2_id) VALUES(8,1,'20000804 11:34:09 AM',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=8),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=9))
INSERT INTO Ýstek(Ýstek_id,Kabul_Red,Tarih_Saat,Kullanýcý1_id,Kullanýcý2_id) VALUES(9,1,'20000804 11:34:09 AM',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=9),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=10))
INSERT INTO Ýstek(Ýstek_id,Kabul_Red,Tarih_Saat,Kullanýcý1_id,Kullanýcý2_id) VALUES(10,1,'20000804 11:34:09 AM',(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=10),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=1))


INSERT INTO Envanter_kaydý(Envanter_id,Aktif,Alýþ_fiyatý,Satýþ_fiyatý,Alýþ_Tarihi,Satýþ_Tarihi,Satýþtamý,Kullanýcý_id,Ýtem_id) VALUES(1,0,100,150,'20100304','20000804',1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=2),(SELECT Ýtem_id FROM Ýtem where Ýtem_isim='f'))
INSERT INTO Envanter_kaydý(Envanter_id,Aktif,Alýþ_fiyatý,Satýþ_fiyatý,Alýþ_Tarihi,Satýþ_Tarihi,Satýþtamý,Kullanýcý_id,Ýtem_id) VALUES(2,0,200,250,'20150804','20000804',0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=1),(SELECT Ýtem_id FROM Ýtem where Ýtem_isim='v'))
INSERT INTO Envanter_kaydý(Envanter_id,Aktif,Alýþ_fiyatý,Satýþ_fiyatý,Alýþ_Tarihi,Satýþ_Tarihi,Satýþtamý,Kullanýcý_id,Ýtem_id) VALUES(3,1,300,400,'20150804','20000804',0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3),(SELECT Ýtem_id FROM Ýtem where Ýtem_isim='c'))
INSERT INTO Envanter_kaydý(Envanter_id,Aktif,Alýþ_fiyatý,Satýþ_fiyatý,Alýþ_Tarihi,Satýþ_Tarihi,Satýþtamý,Kullanýcý_id,Ýtem_id) VALUES(4,0,400,750,'20150804','20000804',1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=4),(SELECT Ýtem_id FROM Ýtem where Ýtem_isim='g'))
INSERT INTO Envanter_kaydý(Envanter_id,Aktif,Alýþ_fiyatý,Satýþ_fiyatý,Alýþ_Tarihi,Satýþ_Tarihi,Satýþtamý,Kullanýcý_id,Ýtem_id) VALUES(5,1,100,130,'20150804','20000804',1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5),(SELECT Ýtem_id FROM Ýtem where Ýtem_isim='a'))
INSERT INTO Envanter_kaydý(Envanter_id,Aktif,Alýþ_fiyatý,Satýþ_fiyatý,Alýþ_Tarihi,Satýþ_Tarihi,Satýþtamý,Kullanýcý_id,Ýtem_id) VALUES(6,1,700,1200,'20150804','20000804',0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=6),(SELECT Ýtem_id FROM Ýtem where Ýtem_isim='b'))
INSERT INTO Envanter_kaydý(Envanter_id,Aktif,Alýþ_fiyatý,Satýþ_fiyatý,Alýþ_Tarihi,Satýþ_Tarihi,Satýþtamý,Kullanýcý_id,Ýtem_id) VALUES(7,0,100,180,'20150804','20000804',0,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=7),(SELECT Ýtem_id FROM Ýtem where Ýtem_isim='j'))
INSERT INTO Envanter_kaydý(Envanter_id,Aktif,Alýþ_fiyatý,Satýþ_fiyatý,Alýþ_Tarihi,Satýþ_Tarihi,Satýþtamý,Kullanýcý_id,Ýtem_id) VALUES(8,1,50,100,'20150804','20000804',1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=1),(SELECT Ýtem_id FROM Ýtem where Ýtem_isim='k'))
INSERT INTO Envanter_kaydý(Envanter_id,Aktif,Alýþ_fiyatý,Satýþ_fiyatý,Alýþ_Tarihi,Satýþ_Tarihi,Satýþtamý,Kullanýcý_id,Ýtem_id) VALUES(9,0,180,340,'20150804','20000804',1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3),(SELECT Ýtem_id FROM Ýtem where Ýtem_isim='f'))
INSERT INTO Envanter_kaydý(Envanter_id,Aktif,Alýþ_fiyatý,Satýþ_fiyatý,Alýþ_Tarihi,Satýþ_Tarihi,Satýþtamý,Kullanýcý_id,Ýtem_id) VALUES(10,0,100,110,'20150804','20000804',1,(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=4),(SELECT Ýtem_id FROM Ýtem where Ýtem_isim='h'))


INSERT INTO Baþarýr(Baþarma_id,Baþarým_Tarihi,Baþarým_id,Kullanýcý_id) Values(1,'20150804 11:34:09 AM',(SELECT Baþarým_id FROM Baþarým WHERE Baþarým_id=1),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=2))
INSERT INTO Baþarýr(Baþarma_id,Baþarým_Tarihi,Baþarým_id,Kullanýcý_id) Values(2,'20150804 11:34:09 AM',(SELECT Baþarým_id FROM Baþarým WHERE Baþarým_id=2),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3))
INSERT INTO Baþarýr(Baþarma_id,Baþarým_Tarihi,Baþarým_id,Kullanýcý_id) Values(3,'20150804 11:34:09 AM',(SELECT Baþarým_id FROM Baþarým WHERE Baþarým_id=3),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=4))
INSERT INTO Baþarýr(Baþarma_id,Baþarým_Tarihi,Baþarým_id,Kullanýcý_id) Values(4,'20150804 11:34:09 AM',(SELECT Baþarým_id FROM Baþarým WHERE Baþarým_id=4),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5))
INSERT INTO Baþarýr(Baþarma_id,Baþarým_Tarihi,Baþarým_id,Kullanýcý_id) Values(5,'20150804 11:34:09 AM',(SELECT Baþarým_id FROM Baþarým WHERE Baþarým_id=5),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=6))
INSERT INTO Baþarýr(Baþarma_id,Baþarým_Tarihi,Baþarým_id,Kullanýcý_id) Values(6,'20150804 11:34:09 AM',(SELECT Baþarým_id FROM Baþarým WHERE Baþarým_id=6),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=7))
INSERT INTO Baþarýr(Baþarma_id,Baþarým_Tarihi,Baþarým_id,Kullanýcý_id) Values(7,'20150804 11:34:09 AM',(SELECT Baþarým_id FROM Baþarým WHERE Baþarým_id=7),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=8))
INSERT INTO Baþarýr(Baþarma_id,Baþarým_Tarihi,Baþarým_id,Kullanýcý_id) Values(8,'20150804 11:34:09 AM',(SELECT Baþarým_id FROM Baþarým WHERE Baþarým_id=8),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=9))
INSERT INTO Baþarýr(Baþarma_id,Baþarým_Tarihi,Baþarým_id,Kullanýcý_id) Values(9,'20150804 11:34:09 AM',(SELECT Baþarým_id FROM Baþarým WHERE Baþarým_id=9),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=10))
INSERT INTO Baþarýr(Baþarma_id,Baþarým_Tarihi,Baþarým_id,Kullanýcý_id) Values(10,'20150804 11:34:09 AM',(SELECT Baþarým_id FROM Baþarým WHERE Baþarým_id=10),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=2))

INSERT INTO Teklif(Teklif_id,Miktar,Envanter_id,Kullanýcý_id) Values(1,100,(SELECT Envanter_id FROM Envanter_kaydý WHERE Envanter_id=1),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=2))
INSERT INTO Teklif(Teklif_id,Miktar,Envanter_id,Kullanýcý_id) Values(2,200,(SELECT Envanter_id FROM Envanter_kaydý WHERE Envanter_id=2),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=3))
INSERT INTO Teklif(Teklif_id,Miktar,Envanter_id,Kullanýcý_id) Values(3,300,(SELECT Envanter_id FROM Envanter_kaydý WHERE Envanter_id=3),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=4))
INSERT INTO Teklif(Teklif_id,Miktar,Envanter_id,Kullanýcý_id) Values(4,400,(SELECT Envanter_id FROM Envanter_kaydý WHERE Envanter_id=4),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5))
INSERT INTO Teklif(Teklif_id,Miktar,Envanter_id,Kullanýcý_id) Values(5,500,(SELECT Envanter_id FROM Envanter_kaydý WHERE Envanter_id=5),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=6))
INSERT INTO Teklif(Teklif_id,Miktar,Envanter_id,Kullanýcý_id) Values(6,600,(SELECT Envanter_id FROM Envanter_kaydý WHERE Envanter_id=6),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=7))
INSERT INTO Teklif(Teklif_id,Miktar,Envanter_id,Kullanýcý_id) Values(7,700,(SELECT Envanter_id FROM Envanter_kaydý WHERE Envanter_id=7),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=8))
INSERT INTO Teklif(Teklif_id,Miktar,Envanter_id,Kullanýcý_id) Values(8,800,(SELECT Envanter_id FROM Envanter_kaydý WHERE Envanter_id=8),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=9))
INSERT INTO Teklif(Teklif_id,Miktar,Envanter_id,Kullanýcý_id) Values(9,900,(SELECT Envanter_id FROM Envanter_kaydý WHERE Envanter_id=9),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=2))
INSERT INTO Teklif(Teklif_id,Miktar,Envanter_id,Kullanýcý_id) Values(10,1000,(SELECT Envanter_id FROM Envanter_kaydý WHERE Envanter_id=1),(SELECT Kullanýcý_id FROM Kullanýcý WHERE Kullanýcý_id=5))


